# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LHCountDownAndLoop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LHCountDownAndLoop
#上/下拉刷新
  pod 'MJRefresh','~> 3.1.0'
  #网络图片读取,及缓存
  pod 'SDWebImage','~> 3.8.1'
  #网络数据读取
  pod 'AFNetworking'
  #模型转换框架
  pod 'YYModel'
  target 'LHCountDownAndLoopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LHCountDownAndLoopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
